# Generated by Django 5.1.2 on 2024-11-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(max_length=8),
        ),
    ]
